name: Deploy Backend to Azure

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Build TypeScript
      run: |
        cd backend
        npm run build
        
    - name: Prepare deployment package
      run: |
        rm -rf deployment-package deployment-package.zip
        mkdir -p deployment-package
        cp -r backend/dist/. deployment-package/
        cp backend/package.json backend/package-lock.json deployment-package/
        mkdir -p deployment-package/config
        cp backend/src/config/schema.sql deployment-package/config/
        cd deployment-package
        zip -r ../deployment-package.zip .
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'fire-door-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: deployment-package.zip
