name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Build TypeScript
      run: |
        cd backend
        npm run build
        
    - name: Create production package
      run: |
        mkdir -p production-package
        cd backend
        npm run build
        cd ..
        # Copy ONLY the compiled JavaScript and essential files
        cp -r backend/dist/* production-package/
        cp backend/package.json production-package/
        cp backend/package-lock.json production-package/ || true
        # Remove ALL source files - Azure won't see TypeScript
        rm -rf production-package/src || true
        rm -rf production-package/tsconfig.json || true
        rm -rf production-package/uploads || true
        # Remove Oryx config files that aren't working
        rm -rf production-package/.oryxignore || true
        rm -rf production-package/oryx-manifest.toml || true
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'fire-door-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: production-package/
