name: Deploy Backend to Azure App Service

on:
  push:
    branches: [ master ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd backend
        npm ci
        
    - name: Build TypeScript
      run: |
        cd backend
        npm run build
        
    - name: Create Azure-ready package
      run: |
        mkdir -p azure-package
        cd backend
        npm run build
        cd ..
        cp -r backend/dist/* azure-package/
        cp backend/package.json azure-package/
        cp backend/package-lock.json azure-package/ || true
        
    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'fire-door-backend'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: azure-package/
